language: node_js

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/my_registrations

node_js:  
  - "8.9.4"

before_script:
  - psql -c 'create database  my_registrations;' -U postgres
  - psql -U postgres -d my_registrations -a -f towns.sql

addons:
    apt:
    packages:
    - postgresql-server-dev-9.2